name: action-jira-story-point-charts
description: Generate story point charts from jira issues and post them to slack
author: insidewhy
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install -g corepack@latest
        corepack enable
        pnpm install --only=production
    - name: Run Action
      shell: bash
      env:
        INPUT_SLACK-CHANNEL: ${{inputs.slack-channel}}
        INPUT_CHARTS: ${{inputs.charts}}
        INPUT_STORY-POINT-ESTIMATE: ${{inputs.story-point-estimate}}
        INPUT_JIRA-USER: ${{inputs.jira-user}}
        INPUT_JIRA-BASE-URL: ${{inputs.jira-base-url}}
        INPUT_JIRA-TOKEN: ${{inputs.jira-token}}
        INPUT_SLACK-TOKEN: ${{inputs.slack-token}}
        INPUT_JIRA-FIELDS: ${{inputs.jira-fields}}
        INPUT_JIRA-STATUSES: ${{inputs.jira-statuses}}
        INPUT_JQL: ${{inputs.jql}}
        INPUT_SUMMARY: ${{inputs.summary}}
        INPUT_WITH-DAILY-DESCRIPTION: ${{inputs.with-daily-description}}
        INPUT_WITH-WEEKLY-DESCRIPTION: ${{inputs.with-weekly-description}}
      run: |
        cd ${{ github.action_path }}
        node lib/index.mjs
branding:
  icon: check-square
  color: blue
inputs:
  slack-channel:
    description: channel id of slack channel to post to
    required: true
  charts:
    description: The charts to generate
  story-point-estimate:
    description: Story point estimate to assign to issues with unset story points
  jira-user:
    description: Jira user that created the auth token
    required: true
  jira-base-url:
    description: Base URL of jira instance to retrieve data from
    required: true
  jira-token:
    description: Jira auth token
    required: true
  slack-token:
    description: Slack bot token
    required: true
  jira-fields:
    description: Customise jira fields used for story points and times
  jira-statuses:
    description: Customise jira statuses
  jql:
    description: The jql used to select issues for the charts
  summary:
    description: A summary text message to include with the charts
  with-weekly-description:
    description: Add a textual summary of changes for this week
  with-daily-description:
    description: Add a textual summary of changes for this day
