name: action-jira-story-point-charts
description: Generate story point charts from jira issues and post them to slack
author: insidewhy
runs:
  using: node20
  main: lib/index.cjs
branding:
  icon: check-square
  color: blue
inputs:
  slack-channel:
    description: channel id of slack channel to post to
    required: true
  charts:
    description: The charts to generate
  story-point-estimate:
    description: Story point estimate to assign to issues with unset story points
  jira-user:
    description: Jira user that created the auth token
    required: true
  jira-base-url:
    description: Base URL of jira instance to retrieve data from
    required: true
  jira-token:
    description: Jira auth token
    required: true
  slack-token:
    description: Slack bot token
    required: true
  jira-fields:
    description: Customise jira fields used for story points and times
  jira-statuses:
    description: Customise jira statuses
  jql:
    description: The jql used to select issues for the charts
  summary:
    description: A summary text message to include with the charts
  with-weekly-description:
    description: Add a textual summary of changes for this week with the given heading
  with-daily-description:
    description: Add a textual summary of changes for this day with the given heading
  store-work-item-history:
    description: Read and store work item history from/to the file system, this is required for the weekly-work-item-changes and daily-work-item-changes charts and also enhances the descriptions provided by with-weekly-description and with-daily-description
