name: action-jira-story-point-charts
description: Generate story point charts from jira issues and post them to slack
author: insidewhy
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        corepack enable
        pnpm install --only=production
    - name: Run Action
      shell: bash
      env:
        INPUT_SLACK-CHANNEL: ${{inputs.slack-channel}}
        INPUT_STORY-POINT-ESTIMATE: ${{inputs.story-point-estimate}}
        INPUT_JIRA-USER: ${{inputs.jira-user}}
        INPUT_JIRA-BASE-URL: ${{inputs.jira-base-url}}
        INPUT_JIRA-TOKEN: ${{inputs.jira-token}}
        INPUT_SLACK-TOKEN: ${{inputs.slack-token}}
      run: |
        cd ${{ github.action_path }}
        node lib/index.mjs
branding:
  icon: check-square
  color: blue
inputs:
  slack-channel:
    description: channel id of slack channel to post to
    required: true
  story-point-estimate:
    description: Story point estimate to assign to issues without story points
  jira-user:
    description: Jira user that created the auth token
    required: true
  jira-base-url:
    description: Base URL of jira instance to retrieve data from
    required: true
  jira-token:
    description: Jira auth token
    required: true
  slack-token:
    description: Slack bot token
    required: true
